services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'example'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './mysql/initdb.d:/docker-entrypoint-initdb.d'
  redis:
    container_name: valkey
    image: valkey/valkey:7.2
    ports:
      - '6379:6379'
    expose:
      - '6379'
  pulsar:
    container_name: pulsar
    image: apachepulsar/pulsar:3.3.0
    environment:
      PULSAR_STANDALONE_USE_ZOOKEEPER: "1"
      BOOKIE_MEM: "-Xms256m -Xmx256m -XX:MaxDirectMemorySize=256m"
      PULSAR_MEM: "-Xms256m -Xmx256m -XX:MaxDirectMemorySize=256m"
    command: "bin/pulsar standalone"
    ports:
      - '6650:6650'
      - '8080:8080'
    expose:
      - '6650'
      - '8080'
