spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
management:
  server:
    port: 9090
  tracing:
    sampling:
      probability: 0.1
server:
  port: 8080
  undertow:
    buffer-size: 16364
    threads:
      io: 32
      worker: 256
logging:
  file:
    name: ../logs/app.log