spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
management:
  server:
    port: 0
  tracing:
    sampling:
      probability: 1
server:
  port: 0
  undertow:
    buffer-size: 1024
    threads:
      io: 1
      worker: 4