spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration
      - org.mybatis.spring.boot.autoconfigure.MybatisLanguageDriverAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration
      - org.springframework.boot.autoconfigure.web.client.RestClientAutoConfiguration
      - org.springframework.boot.autoconfigure.web.reactive.function.client.WebClientAutoConfiguration
      - org.springframework.boot.autoconfigure.web.client.RestTemplateAutoConfiguration
      - org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration
      - org.springframework.boot.autoconfigure.task.TaskSchedulingAutoConfiguration
      - org.springframework.boot.autoconfigure.netty.NettyAutoConfiguration
      - org.springframework.boot.autoconfigure.reactor.ReactorAutoConfiguration
      - org.springframework.boot.autoconfigure.ssl.SslAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.startup.StartupEndpointAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.scheduling.ScheduledTasksEndpointAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.scheduling.ScheduledTasksObservabilityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.observation.web.client.HttpClientObservationsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.web.exchanges.HttpExchangesAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.web.exchanges.HttpExchangesEndpointAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.data.redis.RedisReactiveHealthContributorAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.task.TaskExecutorMetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.startup.StartupTimeMetricsListenerAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.data.RepositoryMetricsAutoConfiguration
  cache:
    type: redis
  data:
    jdbc:
      repositories:
        enabled: false
    redis:
      client-type: lettuce
      lettuce:
        pool:
          enabled: true
          max-active: 20
          max-idle: 20
          max-wait: 2s
          min-idle: 1
      repositories:
        enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      allow-pool-suspension: false
      auto-commit: true
      connection-timeout: 600000
      idle-timeout: 150000
      max-lifetime: 300000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: hikari_def_pool-
    type: com.zaxxer.hikari.HikariDataSource
  dao:
    exceptiontranslation:
      enabled: false
  flyway:
    enabled: false
  jmx:
    enabled: false
  lifecycle:
    timeout-per-shutdown-phase: 30s
  liquibase:
    enabled: false
  main:
    banner-mode: 'off'
    lazy-initialization: true
  mvc:
    converters:
      preferred-json-mapper: jackson
    format:
      date: iso
      date-time: iso-offset
      time: iso-offset
  pulsar:
    function:
      enabled: false
  servlet:
    multipart:
      enabled: false
  sql:
    init:
      mode: never
management:
  auditevents:
    enabled: false
  endpoint:
    auditevents:
      enabled: false
    beans:
      enabled: true
    caches:
      enabled: true
    conditions:
      enabled: true
    configprops:
      enabled: true
    env:
      enabled: true
    flyway:
      enabled: false
    health:
      enabled: true
      group:
        liveness:
          include:
            - ping
          show-components: never
          show-details: never
        readiness:
          include:
            - '*'
          show-components: never
          show-details: never
      logging:
        slow-indicator-threshold: 30s
      probes:
        enabled: false
      show-components: never
      show-details: never
    heapdump:
      enabled: true
    httpexchanges:
      enabled: true
    info:
      enabled: true
    integrationgraph:
      enabled: false
    liquibase:
      enabled: false
    logfile:
      enabled: false
    loggers:
      enabled: true
    mappings:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    quartz:
      enabled: false
    sbom:
      enabled: false
    scheduledtasks:
      enabled: true
    sessions:
      enabled: false
    shutdown:
      enabled: false
    startup:
      enabled: false
    threaddump:
      enabled: true
  endpoints:
    jackson:
      isolated-object-mapper: true
    migrate-legacy-ids: false
    web:
      discovery:
        enabled: true
      exposure:
        include: '*'
  health:
    diskspace:
      enabled: false
  httpexchanges:
    recording:
      enabled: false
  observations:
    annotations:
      enabled: false
  otlp:
    tracing:
      compression: gzip
      timeout: 5s
server:
  compression:
    enabled: false
  error:
    include-binding-errors: never
    include-exception: false
    include-message: never
    include-path: never
    include-stacktrace: never
    whitelabel:
      enabled: true
  servlet:
    encoding:
      charset: UTF-8
    jsp:
      registered: false
    register-default-servlet: false
  undertow:
    always-set-keep-alive: true
    direct-buffers: true
    max-http-post-size: 4MB
logging:
  config: "classpath:/pantheon/logback-spring.xml"
  charset:
    console: UTF-8
    file: UTF-8
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      clean-history-on-start: false
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log
      max-file-size: 50MB
      max-history: 7
      total-size-cap: 1GB
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){blue} %clr(%5p) %clr([%t]){faint} %clr(%logger){magenta}%clr(.%L){blue} %clr(:){faint} %m%n%wEx'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%X{traceId}|%X{spanId}] [%t] %logger %L:%m%n%wEx'
  level:
    org:
      springframework:
        boot:
          context:
            config:
              ConfigDataEnvironmentContributors: trace
              ConfigDataEnvironment: trace