spring:
  main:
    banner-mode: off
    lazy-initialization: true
  jmx:
    enabled: false
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      allow-pool-suspension: false
      idle-timeout: 150000
      max-lifetime: 300000
      connection-timeout: 600000
      minimum-idle: 10
      maximum-pool-size: 20
      pool-name: hikari_def_pool-
  sql:
    init:
      mode: never
  flyway:
    enabled: false
  liquibase:
    enabled: false
  data:
    redis:
      lettuce:
        pool:
          enabled: true
          min-idle: 1
          max-idle: 20
          max-wait: 2s
          max-active: 20
      client-type: lettuce
  mvc:
    converters:
      preferred-json-mapper: jackson
    format:
      date: iso
      date-time: iso-offset
      time: iso-offset
  servlet:
    multipart:
      enabled: false
server:
  compression:
    enabled: false
  error:
    whitelabel:
      enabled: false
    include-binding-errors: never
    include-message: never
    include-path: never
    include-exception: false
    include-stacktrace: never
  servlet:
    encoding:
      charset: UTF-8
    jsp:
      registered: false
    register-default-servlet: false
  tomcat:
    accept-count: 10
    accesslog:
      enabled: false
    background-processor-delay: 5s
    connection-timeout: 5s
    keep-alive-timeout: 10m
    max-connections: 8192
    max-http-form-post-size: 2MB
    max-http-response-header-size: 8KB
    max-swallow-size: 2MB
    max-keep-alive-requests: 5
    processor-cache: 10
    redirect-context-root: true
    mbeanregistry:
      enabled: false
    resource:
      allow-caching: true
      cache-ttl: 1d
    threads:
      max: 10
      min-spare: 10
      max-queue-capacity: 200
    uri-encoding: UTF-8
    use-relative-redirects: false
management:
  auditevents:
    enabled: false
  endpoint:
    beans:
      enabled: true
    caches:
      enabled: true
    auditevents:
      enabled: false
    configprops:
      enabled: true
    conditions:
      enabled: true
    env:
      enabled: true
    flyway:
      enabled: false
    liquibase:
      enabled: false
    health:
      enabled: true
      group:
        readiness:
          include:
            - "*"
          show-details: never
          show-components: never
        liveness:
          include:
            - ping
          show-details: never
          show-components: never
      logging:
        slow-indicator-threshold: 30s
      probes:
        enabled: false
      show-components: never
      show-details: never
    heapdump:
      enabled: true
    httpexchanges:
      enabled: true
    info:
      enabled: true
    integrationgraph:
      enabled: false
    logfile:
      enabled: false
    loggers:
      enabled: true
    mappings:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    quartz:
      enabled: false
    sbom:
      enabled: false
    scheduledtasks:
      enabled: true
    sessions:
      enabled: false
    shutdown:
      enabled: false
    startup:
      enabled: false
    threaddump:
      enabled: true
  endpoints:
    jackson:
      isolated-object-mapper: true
    migrate-legacy-ids: false
    web:
      discovery:
        enabled: true
      exposure:
        include: "*"
  health:
    diskspace:
      enabled: false
  observations:
    annotations:
      enabled: false
  otlp:
    tracing:
      timeout: 5s
      compression: gzip
logging:
  file:
    name: "logs/app.log"
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){blue} %clr(%5p) %clr([%X{traceId}|%X{spanId}]){faint} %clr([%t]){faint} %clr(%logger){magenta}%clr(.%L){blue} %clr(:){faint} %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%X{traceId}|%X{spanId}] [%t] %logger %L:%m%n%wEx"
  charset:
    console: UTF-8
    file: UTF-8
  logback:
    rollingpolicy:
      clean-history-on-start: false
      max-file-size: 50MB
      total-size-cap: 1GB
      max-history: 7
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.log"



