spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
  data:
    redis:
      lettuce:
        pool:
          min-idle: 1
          max-idle: 2
          max-active: 2
server:
  port: 0
  tomcat:
    accept-count: 10
    background-processor-delay: 5s
    connection-timeout: 5s
    keep-alive-timeout: 10m
    max-connections: 8192
    max-keep-alive-requests: 5
    processor-cache: 10
    threads:
      max: 10
      min-spare: 10
      max-queue-capacity: 200
management:
  server:
    port: 0
  tracing:
    sampling:
      probability: 1
