spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    hikari:
      minimum-idle: 10
      maximum-pool-size: 200
  data:
    redis:
      lettuce:
        pool:
          min-idle: 5
          max-idle: 32
          max-active: 32
server:
  port: 8080
  tomcat:
    accept-count: 100
    background-processor-delay: 5s
    connection-timeout: 5s
    keep-alive-timeout: 10m
    max-connections: 8192
    max-keep-alive-requests: 100
    processor-cache: 200
    threads:
      max: 200
      min-spare: 10
      max-queue-capacity: 131072
management:
  server:
    port: 9090
  tracing:
    sampling:
      probability: 0.1
logging:
  file:
    name: "../logs/app.log"